// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaconnector.actions;

import org.eclipse.milo.opcua.sdk.client.OpcUaClient;
import org.eclipse.milo.opcua.sdk.client.nodes.UaNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import opcuaconnector.impl.OpcNode;
import opcuaconnector.impl.MxNodeFactory;
import opcuaconnector.impl.OpcAttributeServiceSet;
import opcuaconnector.impl.ClientManager;
import opcuaconnector.proxies.Node;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetNodeDetails extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use serverConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __serverConfiguration;
	private final opcuaconnector.proxies.ServerConfiguration serverConfiguration;
	private final java.lang.String nodeId;

	public GetNodeDetails(
		IContext context,
		IMendixObject _serverConfiguration,
		java.lang.String _nodeId
	)
	{
		super(context);
		this.__serverConfiguration = _serverConfiguration;
		this.serverConfiguration = _serverConfiguration == null ? null : opcuaconnector.proxies.ServerConfiguration.initialize(getContext(), _serverConfiguration);
		this.nodeId = _nodeId;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		// Create connected client
		OpcUaClient opcClient = ClientManager.getInstance().getOrCreateClient(serverConfiguration, context())
				.getUaClient();

		// Do request
		UaNode opcNode = new OpcAttributeServiceSet(opcClient).getOpcUaNode(new OpcNode(nodeId).getOpcNodeId());

		// Convert to Mendix Objects
		Node mxNode = new MxNodeFactory(opcNode, getContext()).getMxNode();

		// Return Mendix root object
		return mxNode.getMendixObject();

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetNodeDetails";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
