// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import opcuaconnector.impl.ClientManager;
import opcuaconnector.proxies.TestConnectionResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Connects to a server. It returns an object that explains whether the connection was succesfull and IF not, why.
 */
public class ServerConfiguration_Connect extends CustomJavaAction<IMendixObject>
{
	/** @deprecated use serverConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __serverConfiguration;
	private final opcuaconnector.proxies.ServerConfiguration serverConfiguration;

	public ServerConfiguration_Connect(
		IContext context,
		IMendixObject _serverConfiguration
	)
	{
		super(context);
		this.__serverConfiguration = _serverConfiguration;
		this.serverConfiguration = _serverConfiguration == null ? null : opcuaconnector.proxies.ServerConfiguration.initialize(getContext(), _serverConfiguration);
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		try {
			// create client
			ClientManager.getInstance().getOrCreateClient(serverConfiguration, context());

			// Return happy response object
			return createMxTestConnectionResponse(true, null).getMendixObject();
		} catch (Exception e) {
			// Return unhappy response object
			return createMxTestConnectionResponse(false, e).getMendixObject();
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ServerConfiguration_Connect";
	}

	// BEGIN EXTRA CODE
	/**
	 * Creates an object that can be used within Mendix to see whether a connection
	 * can be established
	 * 
	 * @param isSuccess    Whether the connection was successful
	 * @param errorMessage If the connection was not successful, what went wrong
	 * @return A Mendix object that contains the result
	 */
	private TestConnectionResponse createMxTestConnectionResponse(Boolean isSuccess, Exception error) {
		TestConnectionResponse response = new TestConnectionResponse(context());
		response.setisSuccess(isSuccess);
		response.setErrorMessage(error != null ? error.getMessage() : null);
		return response;
	}
	// END EXTRA CODE
}
