// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import opcuaconnector.impl.ClientCertificateValidator;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ServerCertificate_AddToTrustList extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use serverCertificate.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __serverCertificate;
	private final opcuaconnector.proxies.ServerCertificate serverCertificate;

	public ServerCertificate_AddToTrustList(
		IContext context,
		IMendixObject _serverCertificate
	)
	{
		super(context);
		this.__serverCertificate = _serverCertificate;
		this.serverCertificate = _serverCertificate == null ? null : opcuaconnector.proxies.ServerCertificate.initialize(getContext(), _serverCertificate);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ClientCertificateValidator.getInstance().trustCertificate(serverCertificate, getContext());

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ServerCertificate_AddToTrustList";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
