// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package opcuaconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import opcuaconnector.impl.ClientManager;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This action makes sure that a server configurations is also removed from the client. [Note that if a Server configuration is deleted before it is connected, that is either before finishing the wizard or before first usage of a call after start up], the log messages will show that it did not need to be deleted. This is as expected.
 */
public class ServerConfiguration_Disconnect extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use serverConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __serverConfiguration;
	private final opcuaconnector.proxies.ServerConfiguration serverConfiguration;

	public ServerConfiguration_Disconnect(
		IContext context,
		IMendixObject _serverConfiguration
	)
	{
		super(context);
		this.__serverConfiguration = _serverConfiguration;
		this.serverConfiguration = _serverConfiguration == null ? null : opcuaconnector.proxies.ServerConfiguration.initialize(getContext(), _serverConfiguration);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		ClientManager.getInstance().deleteClient(serverConfiguration);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ServerConfiguration_Disconnect";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
